// angularGraphql/src/app/components/query/query.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-query',
  templateUrl: './query.component.html'
})
export class QueryComponent implements OnInit {
  @Input() query;
  @Input('data') data;
  @Output() updateData = new EventEmitter<string>();
  constructor() { }
  ngOnInit(): void { }
  updated() {
    this.updateData.emit(this.query)
  }
}

<div>
 <div class="row mt-4">
  <div class="col-2">
   <h4>Consulta</h4>
   <pre>{{query}}</pre>
  </div>
  <div class="col-4">
   <h4>Edita tu Consulta</h4>
   <label>
    <textarea [(ngModel)]=query cols="40" rows="20"></textarea>
   </label>
  </div>
  <div class="col-4">
   <pre>{{data}}</pre>
  </div>
  <div class="col-2">
   <br />
   <br />
   <br />
   <button class="btn btn-secondary" (click)="updated()">Ejecutar query</button>
  </div>
 </div>
</div>

// graphqlreact/src/components/query.jsx
import React from 'react';
import { Button } from 'react-bootstrap';

const Query = (props) => {

 return (
  < div className="App" >
   <br />
   <div className="row mt-4">
    <div className="col-2">
     <h4>Consulta</h4>
     <pre>{props.queryGetAllUsers}</pre>
    </div>
    <div className="col-4">
     <h4>Edita tu Consulta</h4>
     <label>
      <textarea value={props.queryGetAllUsers} name="getAllUsers" cols="40" rows="20" onChange={(event) => props.onChange(event, props.type)}></textarea>
     </label>
    </div>
    <div className="col-4">
     <div>
      {props.userList !== undefined ?
       <div ><pre>{JSON.stringify(props.userList, null, 2)}</pre></div>
       : <>parametros erroneos</>
      }
     </div>
    </div>
    <div className="col-2 ">
     <Button className="mt-5" variant="secondary" onClick={props.getUsers}>Ejecutar query</Button>
    </div>
   </div>
  </div >
 )
}

export default Query;
